
DROP TABLE EMPLOYEE PURGE;

CREATE TABLE EMPLOYEE(
EMPNO NUMBER(3),
ENAME VARCHAR2(15),
SALARY NUMBER(7,2),
DATEOFJOIN DATE,
JOB VARCHAR2(10),
DEPTNO NUMBER(2)
);

DESCRIBE EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(&EMPNO,'&ENAME',&SALARY,TO_DATE('&DATEOFJOIN','DD-MON-YYYY'),'&JOB',&DEPTNO);
/

SELECT * FROM EMPLOYEE;

SELECT EMPNO,ENAME,SALARY FROM EMPLOYEE;

SELECT EMPNO,ENAME,SALARY,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE SALARY < 10000;

SELECT * FROM EMPLOYEE WHERE SALARY > 10000;

SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 8000 AND 12000;

SELECT * FROM EMPLOYEE WHERE SALARY > 10000 AND SALARY < 15000;

SELECT * FROM EMPLOYEE WHERE EMPNO IN (102,110,114);

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'M%';

SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%I';

SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%I%';

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'S%H';

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'S_____H';

SELECT EMPNO,ENAME,SALARY,DEPTNO FROM EMPLOYEE WHERE DEPTNO = 10;

SELECT * FROM EMPLOYEE WHERE JOB = 'CLERK' AND DEPTNO = 20;

SELECT * FROM EMPLOYEE WHERE DATEOFJOIN = TO_DATE('01-APR-1980','DD-MON-YYYY');

SELECT * FROM EMPLOYEE WHERE JOB = 'CLERK' AND DEPTNO IN (10,20);

SELECT * FROM EMPLOYEE WHERE JOB = 'SALESMAN' AND SALARY > 8000;

SELECT * FROM EMPLOYEE WHERE JOB = 'MANAGER' 
AND DATEOFJOIN = TO_DATE('01-JUL-1980','DD-MON-YYYY');

SELECT DATEOFJOIN,SALARY,ENAME,DEPTNO 
FROM EMPLOYEE 
WHERE JOB IN ('CLERK','ANALYST') 
AND DEPTNO IN (10,30);

SELECT SALARY,ENAME,DEPTNO,JOB 
FROM EMPLOYEE 
WHERE ENAME LIKE 'R%' 
AND DEPTNO IN (10,20);

SELECT * FROM EMPLOYEE 
WHERE DATEOFJOIN BETWEEN 
TO_DATE('01-JAN-1988','DD-MON-YYYY') 
AND TO_DATE('01-FEB-1990','DD-MON-YYYY');

